stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip3 install -U folia

test_morphosyntax:
  stage: test
  before_script:
    - export TERM=xterm
  script: 
    - echo "Testing the morphosyntax reannotation script"
    - ./test/test_reannotate-morphosyntax.sh

test_all:
  stage: test
  before_script:
    - export TERM=xterm
  script:
    - echo "Testing if we can run all scripts to completion"
    - ./test/test.sh
    