stages:
  - test
  - deploy

test_morphosyntax:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip3 install -U folia
    - export TERM=xterm
  script: 
    - echo "Testing the morphosyntax reannotation script"
    - ./test/test_reannotate-morphosyntax.sh
  artifacts:
    paths:
      - ./test/data_reannotation/REANNOTATION/
    expire_in: 2 days

test_all:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip3 install -U folia
    - export TERM=xterm
  script:
    - echo "Testing if we can run all scripts to completion"
    - ./test/test.sh

release:
  stage: deploy
  script:
    - echo "Next release for PARSEME Shared Task"
    - ./test/release_script.sh
  only:
    - schedules
    